// ข้อความ UI ทั่วไปของ client (ไม่ใช่เนื้อหาเกม — เนื้อหาเกมอยู่ใน content/)

export const UI = {
  level: (lv: number) => `Lv. ${lv}`,
  menu: "เมนู",
  close: "ปิด",
  keyItems: "ของสำคัญ",
  noKeyItems: "ยังไม่มีของสำคัญ",
  comingSoon: "เร็ว ๆ นี้",
  menuItems: [
    { label: "คลังของฉัน", phase: 6 },
    { label: "สมุดภาพ", phase: 6 },
    { label: "กระเป๋า", phase: 7 },
    { label: "เควส", phase: 10 },
    { label: "ตั้งค่า", phase: 13 },
  ],
  needItem: (itemName: string, itemDesc: string) => `ยังไปต่อไม่ได้ ต้องมี "${itemName}" ก่อน (${itemDesc})`,
  cannotPass: "ไปทางนั้นไม่ได้",
  login: {
    title: "เข้าสู่เกาะนิเวศา",
    classCode: "รหัสห้องเรียน",
    classCodeHint: "ขอรหัสจากครู",
    nickname: "ชื่อเล่น",
    pin: "PIN 4 หลัก",
    pinHint: "ครั้งแรก: ตั้ง PIN เองแล้วจำไว้ใช้ครั้งต่อไป",
    submit: "เข้าเล่น",
    checking: "กำลังตรวจสอบ…",
  },
  starter: {
    title: "เลือกมอนสเตอร์คู่หู",
    subtitle: "เลือกได้ 1 ตัว คู่หูจะร่วมผจญภัยไปกับเธอ",
    choose: (name: string) => `เลือก${name}`,
    avatarTitle: "เลือกตัวละครของเธอ",
    avatar: "ตัวละคร",
  },
  lobby: {
    hello: (name: string) => `สวัสดี ${name}`,
    partner: (name: string, lv: number) => `คู่หู: ${name} Lv. ${lv}`,
    quick: "จับคู่อัตโนมัติ",
    quickHint: "เข้าห้องที่ว่างของห้องเรียนเดียวกัน",
    create: "สร้างห้องใหม่",
    createHint: "ได้รหัส 6 หลักไว้ชวนเพื่อน",
    code: "รหัสห้อง 6 หลัก",
    join: "เข้าห้อง",
    logout: "ออกจากระบบ",
    reconnecting: "กำลังกลับเข้าห้องเดิม…",
  },
  room: {
    chip: (code: string, n: number, max: number) => `ห้อง ${code} · ${n}/${max}`,
    leave: "ออกจากห้อง",
    logout: "ออกจากระบบ",
    replaced: "บัญชีนี้เข้าเล่นจากที่อื่น จึงถูกให้ออกจากห้อง",
    reconnecting: "การเชื่อมต่อหลุด กำลังเชื่อมต่อใหม่…",
    reconnectFailed: "เชื่อมต่อห้องเดิมไม่สำเร็จ",
    left: "ออกจากห้องแล้ว",
  },
  chat: "แชท",
  dev: {
    title: "โหมดทดสอบ",
    give: "ให้",
    remove: "เอาออก",
  },
} as const;
