// ข้อความ UI ทั่วไปของ client (ไม่ใช่เนื้อหาเกม — เนื้อหาเกมอยู่ใน content/)

export const UI = {
  level: (lv: number) => `Lv. ${lv}`,
  menu: "เมนู",
  close: "ปิด",
  keyItems: "ของสำคัญ",
  noKeyItems: "ยังไม่มีของสำคัญ",
  menuItems: [
    { id: "collection", label: "คลังของฉัน", phase: 6 },
    { id: "catalog", label: "สมุดภาพ", phase: 6 },
    { id: "bag", label: "กระเป๋า", phase: 7 },
    { id: "quests", label: "เควส", phase: 10 },
    { id: "settings", label: "ตั้งค่า", phase: 13 },
  ],
  soon: (phase: number) => `เร็ว ๆ นี้ (เฟส ${phase})`,
  needItem: (itemName: string, itemDesc: string) => `ยังไปต่อไม่ได้ ต้องมี "${itemName}" ก่อน (${itemDesc})`,
  cannotPass: "ไปทางนั้นไม่ได้",
  login: {
    title: "เข้าสู่เกาะนิเวศา",
    classCode: "รหัสห้องเรียน",
    classCodeHint: "ขอรหัสจากครู",
    nickname: "ชื่อเล่น",
    pin: "PIN 4 หลัก",
    pinHint: "ครั้งแรก: ตั้ง PIN เองแล้วจำไว้ใช้ครั้งต่อไป",
    submit: "เข้าเล่น",
    checking: "กำลังตรวจสอบ…",
  },
  starter: {
    title: "เลือกมอนสเตอร์คู่หู",
    subtitle: "เลือกได้ 1 ตัว คู่หูจะร่วมผจญภัยไปกับเธอ",
    choose: (name: string) => `เลือก${name}`,
    avatarTitle: "เลือกตัวละครของเธอ",
    avatar: "ตัวละคร",
  },
  lobby: {
    hello: (name: string) => `สวัสดี ${name}`,
    partner: (name: string, lv: number) => `คู่หู: ${name} Lv. ${lv}`,
    quick: "จับคู่อัตโนมัติ",
    quickHint: "เข้าห้องที่ว่างของห้องเรียนเดียวกัน",
    create: "สร้างห้องใหม่",
    createHint: "ได้รหัส 6 หลักไว้ชวนเพื่อน",
    code: "รหัสห้อง 6 หลัก",
    join: "เข้าห้อง",
    logout: "ออกจากระบบ",
    reconnecting: "กำลังกลับเข้าห้องเดิม…",
  },
  room: {
    chip: (code: string, n: number, max: number) => `ห้อง ${code} · ${n}/${max}`,
    leave: "ออกจากห้อง",
    logout: "ออกจากระบบ",
    replaced: "บัญชีนี้เข้าเล่นจากที่อื่น จึงถูกให้ออกจากห้อง",
    reconnecting: "การเชื่อมต่อหลุด กำลังเชื่อมต่อใหม่…",
    reconnectFailed: "เชื่อมต่อห้องเดิมไม่สำเร็จ",
    left: "ออกจากห้องแล้ว",
  },
  chat: "แชท",
  collection: {
    title: "คลังของฉัน",
    storage: (n: number, cap: number) => `คลัง ${n}/${cap}`,
    boxedCount: (n: number) => `กล่องพัก ${n}`,
    all: "ทั้งหมด",
    element: "ธาตุ",
    rarity: "ความหายาก",
    form: "ร่าง",
    formN: (n: number) => `ร่าง ${n}`,
    habitat: "ที่อยู่",
    where: "อยู่ที่",
    inTeam: "ในทีม",
    inStorage: "ในคลัง",
    inBox: "กล่องพัก",
    sort: "เรียง",
    sortLevel: "เลเวล",
    sortPower: "ค่าพลังรวม",
    sortNew: "ได้ล่าสุด",
    empty: "ไม่มีมอนสเตอร์ที่ตรงกับตัวกรอง",
    partner: "คู่หู",
    teamSlot: (n: number) => `ทีม ${n + 1}`,
    boxed: "กล่องพัก",
    back: "‹ กลับ",
    stats: "ค่าพลัง",
    statNames: { hp: "HP", atk: "โจมตี", def: "ป้องกัน", spd: "ความเร็ว" } as Record<string, string>,
    total: (n: number) => `รวม ${n}`,
    exp: (n: number, next: number) => `EXP ${n}/${next}`,
    moves: "ท่า",
    emptyMove: "ช่องว่าง",
    equipment: "ไอเท็มที่สวม",
    slots: { head: "หัว", body: "ตัว", charm: "เครื่องราง" } as Record<string, string>,
    noItem: "ว่าง",
    role: "บทบาทในระบบนิเวศ",
    origin: "ที่มา",
    originStarter: "มอนตั้งต้น",
    originWild: (zone: string) => `จับได้ที่${zone}`,
    originOther: "ได้จากรางวัล",
    parents: "พ่อแม่",
    obtained: (d: string) => `ได้เมื่อ ${d}`,
    setPartner: "ตั้งเป็นคู่หู",
    isPartner: "เป็นคู่หูอยู่",
    addTeam: "ใส่ทีม",
    removeTeam: "เอาออกจากทีม",
    breed: "ส่งไปผสม",
    equip: "สวมไอเท็ม",
    lock: "🔒 ล็อกกันปล่อย",
    unlock: "🔓 ปลดล็อก",
    release: "ปล่อยคืนธรรมชาติ",
    unbox: "ย้ายเข้าคลัง",
    rename: "✎ ตั้งชื่อ",
    renamePlaceholder: "ชื่อเล่น (เว้นว่าง = ใช้ชื่อพันธุ์)",
    save: "บันทึก",
    cancel: "ยกเลิก",
    releaseConfirm: (name: string, pts: number) => `ปล่อย${name}คืนธรรมชาติใช่ไหม? ได้แต้มอนุรักษ์ +${pts} (เอาคืนไม่ได้)`,
    released: (name: string, pts: number) => `ปล่อย${name}คืนธรรมชาติแล้ว ได้แต้มอนุรักษ์ +${pts}`,
    releaseLocked: "ปลดล็อกก่อนจึงปล่อยได้",
    releaseTeam: "เอาออกจากทีมก่อนจึงปล่อยได้",
    partnerSet: (name: string) => `${name} เป็นคู่หูแล้ว`,
    loading: "กำลังโหลด…",
  },
  catalog: {
    title: "สมุดภาพ",
    progress: (n: number, total: number) => `${n}/${total} ช่อง`,
    tabMonsters: "มอนสเตอร์",
    tabRewards: "รางวัลสะสม",
    unknown: "???",
    hint: (text: string) => `ใบ้: ${text}`,
    seen: "เคยพบ",
    owned: "มีแล้ว",
    notOwned: "ยังไม่มี — จับหรือเลี้ยงให้ถึงร่างนี้เพื่อดูข้อมูลครบ",
    neverSeen: "ยังไม่เคยพบ",
    baseStats: "ค่าพลังพื้นฐาน",
    didYouKnow: "รู้ไหม?",
    forms: "สายวิวัฒน์",
    habitatLand: "บนบก",
    habitatWater: "ในน้ำ",
    reward: (pct: number) => `ครบ ${pct}%`,
    claimed: "ได้รับแล้ว",
    locked: "ยังไม่ถึง",
    titleLabel: "ฉายา",
    frameLabel: "กรอบโปรไฟล์",
    use: "ใช้",
    using: "กำลังใช้",
    unuse: "เลิกใช้",
    coins: (n: number) => `${n} เหรียญ`,
    tier: { common: "ธรรมดา", good: "ดี", rare: "หายาก" } as Record<string, string>,
    unlocked: (pct: number) => `สมุดภาพครบ ${pct}%! ได้รับรางวัล`,
    rarity: { normal: "ธรรมดา", rare: "หายาก", legend: "ตำนาน" } as Record<string, string>,
  },
  notice: {
    team_healed: "น้ำพุฟื้นพลังให้มอนสเตอร์ในทีมจนเต็มแล้ว",
    no_questions: "ยังไม่มีคำถามที่ครูอนุมัติ จึงยังต่อสู้ไม่ได้",
  } as Record<string, string>,
  battle: {
    appear: (name: string, lv: number) => `${name} Lv. ${lv} ปรากฏตัว!`,
    choose: "จะใช้ท่าไหนดี?",
    waiting: "รอสักครู่…",
    switchBtn: "สลับตัว",
    switchTitle: "เลือกมอนสเตอร์ที่จะออกไปสู้",
    switchHint: "สลับตัวเสีย 1 เทิร์น",
    flee: "หนี",
    back: "ย้อนกลับ",
    cooldown: (n: number) => `รอ ${n} เทิร์น`,
    power: (p: number) => `พลัง ${p}`,
    fainted: "หมดแรง",
    active: "กำลังสู้",
    question: "ตอบให้ถูกเพื่อโจมตี!",
    choiceLabels: ["ก", "ข", "ค", "ง"],
    trueLabel: "ถูก",
    falseLabel: "ผิด",
    numericPlaceholder: "พิมพ์ตัวเลข",
    submit: "ตอบ",
    item: "ใช้ไอเท็ม",
    itemSoon: "ใช้ไอเท็มได้ในเฟส 7",
    timeUp: "หมดเวลา!",
    seconds: (n: number) => `${n} วิ`,
    correct: "ถูกต้อง!",
    quick: "ตอบไว! พลังโจมตี ×1.2",
    wrong: "ยังไม่ถูก",
    timedOut: "หมดเวลา",
    answerIs: (text: string) => `คำตอบที่ถูก: ${text}`,
    explanation: "คำอธิบาย",
    next: "ต่อไป",
    nextIn: (n: number) => `ต่อไป (${n})`,
    missed: "พลาด!",
    super: "ได้ผลดีมาก!",
    weak: "ไม่ค่อยได้ผล…",
    decay: (n: number) => `ย่อยสลาย ×${n}`,
    stat: { hp: "HP", atk: "ATK", def: "DEF", spd: "SPD" } as Record<string, string>,
    faint: (name: string) => `${name} หมดแรง!`,
    go: (name: string) => `ไปเลย ${name}!`,
    win: "ชนะแล้ว!",
    caught: (name: string) => `ได้${name}มาเป็นเพื่อนแล้ว!`,
    newSpecies: "ใหม่! บันทึกลงสมุดภาพ",
    toTeam: "เข้าร่วมทีมแล้ว",
    toStorage: "ทีมเต็ม ส่งไปที่คลังแล้ว",
    toBox: "คลังเต็ม ฝากไว้ที่กล่องพักก่อน",
    lose: "คู่หูหมดแรงทั้งทีม…",
    loseHint: "ไม่เป็นไรนะ! พากลับไปพักที่น้ำพุ มอนสเตอร์หายเหนื่อยแล้ว ไม่เสียของใด ๆ",
    fled: "หนีมาได้อย่างปลอดภัย",
    score: (c: number, n: number) => `ตอบถูก ${c}/${n} ข้อ`,
    playerExp: (n: number) => `EXP ผู้เล่น +${n}`,
    coins: (n: number) => `เหรียญ +${n}`,
    monsterExp: (name: string, n: number) => `${name} EXP +${n}`,
    levelUp: (name: string, from: number, to: number) => `${name} เลเวลอัป! Lv. ${from} → ${to}`,
    newMove: (name: string) => `เรียนรู้ท่าใหม่: ${name}`,
    playerLevelUp: (from: number, to: number) => `เลเวลผู้เล่นอัป! Lv. ${from} → ${to}`,
    backToMap: "กลับสู่แผนที่",
    busy: "มอนตัวนี้กำลังต่อสู้กับคนอื่นอยู่",
  },
  dev: {
    title: "โหมดทดสอบ",
    give: "ให้",
    remove: "เอาออก",
    summon: "⚔ เรียกมอนป่ามาข้างหน้า",
  },
} as const;
