// ข้อความ UI ทั่วไปของ client (ไม่ใช่เนื้อหาเกม — เนื้อหาเกมอยู่ใน content/)

export const UI = {
  level: (lv: number) => `Lv. ${lv}`,
  menu: "เมนู",
  close: "ปิด",
  keyItems: "ของสำคัญ",
  noKeyItems: "ยังไม่มีของสำคัญ",
  menuItems: [
    { id: "collection", label: "คลังของฉัน", phase: 6 },
    { id: "catalog", label: "สมุดภาพ", phase: 6 },
    { id: "bag", label: "กระเป๋า", phase: 7 },
    { id: "lab", label: "ไข่และแล็บ", phase: 8 },
    { id: "quests", label: "เควส", phase: 10 },
    { id: "settings", label: "ตั้งค่า", phase: 13 },
  ],
  soon: (phase: number) => `เร็ว ๆ นี้ (เฟส ${phase})`,
  needItem: (itemName: string, itemDesc: string) => `ยังไปต่อไม่ได้ ต้องมี "${itemName}" ก่อน (${itemDesc})`,
  cannotPass: "ไปทางนั้นไม่ได้",
  login: {
    title: "เข้าสู่เกาะนิเวศา",
    classCode: "รหัสห้องเรียน",
    classCodeHint: "ขอรหัสจากครู",
    nickname: "ชื่อเล่น",
    pin: "PIN 4 หลัก",
    pinHint: "ครั้งแรก: ตั้ง PIN เองแล้วจำไว้ใช้ครั้งต่อไป",
    submit: "เข้าเล่น",
    checking: "กำลังตรวจสอบ…",
  },
  starter: {
    title: "เลือกมอนสเตอร์คู่หู",
    subtitle: "เลือกได้ 1 ตัว คู่หูจะร่วมผจญภัยไปกับเธอ",
    choose: (name: string) => `เลือก${name}`,
    avatarTitle: "เลือกตัวละครของเธอ",
    avatar: "ตัวละคร",
  },
  lobby: {
    hello: (name: string) => `สวัสดี ${name}`,
    partner: (name: string, lv: number) => `คู่หู: ${name} Lv. ${lv}`,
    quick: "จับคู่อัตโนมัติ",
    quickHint: "เข้าห้องที่ว่างของห้องเรียนเดียวกัน",
    create: "สร้างห้องใหม่",
    createHint: "ได้รหัส 6 หลักไว้ชวนเพื่อน",
    code: "รหัสห้อง 6 หลัก",
    join: "เข้าห้อง",
    logout: "ออกจากระบบ",
    reconnecting: "กำลังกลับเข้าห้องเดิม…",
  },
  room: {
    chip: (code: string, n: number, max: number) => `ห้อง ${code} · ${n}/${max}`,
    leave: "ออกจากห้อง",
    logout: "ออกจากระบบ",
    replaced: "บัญชีนี้เข้าเล่นจากที่อื่น จึงถูกให้ออกจากห้อง",
    reconnecting: "การเชื่อมต่อหลุด กำลังเชื่อมต่อใหม่…",
    reconnectFailed: "เชื่อมต่อห้องเดิมไม่สำเร็จ",
    left: "ออกจากห้องแล้ว",
  },
  chat: "แชท",
  collection: {
    title: "คลังของฉัน",
    storage: (n: number, cap: number) => `คลัง ${n}/${cap}`,
    boxedCount: (n: number) => `กล่องพัก ${n}`,
    all: "ทั้งหมด",
    element: "ธาตุ",
    rarity: "ความหายาก",
    form: "ร่าง",
    formN: (n: number) => `ร่าง ${n}`,
    habitat: "ที่อยู่",
    where: "อยู่ที่",
    inTeam: "ในทีม",
    inStorage: "ในคลัง",
    inBox: "กล่องพัก",
    sort: "เรียง",
    sortLevel: "เลเวล",
    sortPower: "ค่าพลังรวม",
    sortNew: "ได้ล่าสุด",
    empty: "ไม่มีมอนสเตอร์ที่ตรงกับตัวกรอง",
    partner: "คู่หู",
    teamSlot: (n: number) => `ทีม ${n + 1}`,
    boxed: "กล่องพัก",
    back: "‹ กลับ",
    stats: "ค่าพลัง",
    statNames: { hp: "HP", atk: "โจมตี", def: "ป้องกัน", spd: "ความเร็ว" } as Record<string, string>,
    total: (n: number) => `รวม ${n}`,
    exp: (n: number, next: number) => `EXP ${n}/${next}`,
    moves: "ท่า",
    emptyMove: "ช่องว่าง",
    equipment: "ไอเท็มที่สวม",
    slots: { head: "หัว", body: "ตัว", charm: "เครื่องราง" } as Record<string, string>,
    noItem: "ว่าง",
    role: "บทบาทในระบบนิเวศ",
    origin: "ที่มา",
    originStarter: "มอนตั้งต้น",
    originWild: (zone: string) => `จับได้ที่${zone}`,
    originOther: "ได้จากรางวัล",
    parents: "พ่อแม่",
    obtained: (d: string) => `ได้เมื่อ ${d}`,
    setPartner: "ตั้งเป็นคู่หู",
    isPartner: "เป็นคู่หูอยู่",
    addTeam: "ใส่ทีม",
    removeTeam: "เอาออกจากทีม",
    breed: "ส่งไปผสม",
    equip: "สวมไอเท็ม",
    lock: "🔒 ล็อกกันปล่อย",
    unlock: "🔓 ปลดล็อก",
    release: "ปล่อยคืนธรรมชาติ",
    unbox: "ย้ายเข้าคลัง",
    rename: "✎ ตั้งชื่อ",
    renamePlaceholder: "ชื่อเล่น (เว้นว่าง = ใช้ชื่อพันธุ์)",
    save: "บันทึก",
    cancel: "ยกเลิก",
    releaseConfirm: (name: string, pts: number) => `ปล่อย${name}คืนธรรมชาติใช่ไหม? ได้แต้มอนุรักษ์ +${pts} (เอาคืนไม่ได้)`,
    released: (name: string, pts: number) => `ปล่อย${name}คืนธรรมชาติแล้ว ได้แต้มอนุรักษ์ +${pts}`,
    releaseLocked: "ปลดล็อกก่อนจึงปล่อยได้",
    releaseTeam: "เอาออกจากทีมก่อนจึงปล่อยได้",
    partnerSet: (name: string) => `${name} เป็นคู่หูแล้ว`,
    loading: "กำลังโหลด…",
  },
  bag: {
    title: "กระเป๋า",
    tabs: { equipment: "ของสวมใส่", consumable: "ใช้ได้", key: "ของสำคัญ" } as Record<string, string>,
    empty: "ยังไม่มีไอเท็มในหมวดนี้",
    qty: (n: number) => `×${n}`,
    use: "ใช้",
    equipTo: "สวมให้…",
    open: "เปิด",
    pickMonster: "เลือกมอนสเตอร์",
    pickHint: (item: string) => `จะใช้${item}กับตัวไหน?`,
    fieldOnly: "ใช้ได้ตอนต่อสู้/ตอบคำถามเท่านั้น",
    soon: "ยังใช้ไม่ได้ในเวอร์ชันนี้",
    healed: (name: string, n: number) => `${name} ฟื้น HP +${n}`,
    levelUp: (name: string, from: number, to: number) => `${name} เลเวลอัป! Lv. ${from} → ${to}`,
    chest: "เปิดหีบสมบัติแล้ว ได้รับ",
    equipped: (item: string, name: string) => `${name} สวม${item}แล้ว`,
    wallet: (coins: number, pts: number) => `🪙 ${coins.toLocaleString("th-TH")} · 🌿 ${pts.toLocaleString("th-TH")}`,
    usableIn: { battle: "ต่อสู้", question: "ตอบคำถาม", field: "นอกการต่อสู้" } as Record<string, string>,
  },
  equip: {
    choose: (slot: string) => `เลือกไอเท็มช่อง${slot}`,
    none: "ไม่มีไอเท็มช่องนี้ในกระเป๋า — ซื้อได้ที่ร้านค้าในหมู่บ้าน",
    unequip: "ถอด",
    change: "เปลี่ยน",
  },
  shop: {
    talk: (name: string) => `🛒 คุยกับ${name}`,
    greeting: "มาแล้วเหรอจ๊ะ! วันนี้อยากได้อะไรดี",
    coinsTab: "ซื้อด้วยเหรียญ",
    pointsTab: "แลกแต้มอนุรักษ์",
    buy: "ซื้อ",
    exchange: "แลก",
    price: (n: number, currency: "coins" | "points") => (currency === "coins" ? `🪙 ${n}` : `🌿 ${n}`),
    bought: (item: string, n: number) => `ได้${item} ×${n} แล้ว`,
    have: (n: number) => `มีอยู่ ${n}`,
    tierCommon: "ขั้นธรรมดา",
  },
  evolution: {
    button: "✨ พัฒนาร่าง",
    notReady: (lv: number) => `พัฒนาร่างได้เมื่อถึงเลเวล ${lv}`,
    maxForm: "พัฒนาร่างครบแล้ว",
    title: "บททดสอบพัฒนาร่าง",
    intro: (need: number, topic: string) => `ตอบถูกติดกัน ${need} ข้อ จากหัวข้อ "${topic}" (หัวข้อที่เธอยังพลาดบ่อย) ผิดได้ ลองใหม่ได้ทันที`,
    streak: (n: number, need: number) => `ถูกติดกัน ${n}/${need}`,
    reset: "ไม่เป็นไร! เริ่มนับใหม่ ลองอีกข้อนะ",
    success: "พัฒนาร่างสำเร็จ!",
    fromTo: (a: string, b: string) => `${a} → ${b}`,
    newMove: (name: string) => `ได้ท่าใหม่: ${name}`,
    done: "เยี่ยมเลย!",
    cancel: "ไว้ทีหลัง",
  },
  lab: {
    title: "ห้องแล็บผสมพันธุ์",
    talk: (name: string) => `🧪 คุยกับ${name}`,
    greeting: "ยินดีต้อนรับสู่ห้องแล็บ! เลือกมอนสเตอร์ระดับเดียวกัน 2 ตัวมาผสม แล้วตอบคำถามให้ถูกเพื่อฟักไข่นะ",
    farGreeting: "ดูไข่และสูตรได้จากทุกที่ แต่ต้องมาที่ห้องแล็บในหมู่บ้านจึงจะผสมได้",
    tabs: { eggs: "ไข่", breed: "ผสม", recipes: "สูตรและ pity" } as Record<string, string>,
    eggSlots: (n: number, max: number) => `ไข่ ${n}/${max}`,
    emptySlot: "ช่องว่าง",
    eggRarity: { normal: "ไข่ธรรมดา", rare: "ไข่หายาก", legend: "ไข่ตำนาน" } as Record<string, string>,
    progress: (n: number, need: number) => `ตอบถูก ${n}/${need}`,
    progressHint: "คำตอบถูกจากทุกกิจกรรมนับให้ไข่ทุกฟองพร้อมกัน",
    parents: (a: string, b: string) => `พ่อแม่: ${a} × ${b}`,
    hatch: "🐣 ฟักไข่",
    hatching: "ไข่กำลังแตก…",
    hatched: (name: string) => `${name} ฟักออกมาแล้ว!`,
    toBox: "คลังเต็ม ฝากไว้ที่กล่องพักก่อน",
    newSpecies: "ใหม่! บันทึกลงสมุดภาพ",
    parentA: "พ่อ/แม่ตัวที่ 1",
    parentB: "พ่อ/แม่ตัวที่ 2",
    pick: "เลือกมอนสเตอร์",
    pickTitle: "เลือกพ่อหรือแม่",
    pickEmpty: "ยังไม่มีมอนสเตอร์ที่ผสมได้",
    change: "เปลี่ยน",
    breed: "🧬 ผสม",
    needLab: "ต้องมาที่ห้องแล็บในหมู่บ้านก่อนจึงผสมได้",
    rules: (tier: string, playerLv: number, parentLv: number, cooldown: number) =>
      `${tier}: ปลดล็อกที่เลเวลผู้เล่น ${playerLv} · พ่อแม่เลเวล ${parentLv}+ · พ่อแม่ไม่หาย แต่พัก ${cooldown} นาที`,
    tierName: { normal: "ธรรมดา + ธรรมดา", rare: "หายาก + หายาก" } as Record<string, string>,
    cooldown: (min: number) => `พักอีก ${min} นาที`,
    tooLow: (lv: number) => `ต้องเลเวล ${lv}+`,
    notBreedable: "ผสมไม่ได้",
    previewKnown: "ตรงสูตรที่ค้นพบแล้ว! มีโอกาสได้",
    previewUnknown: "ผสมแล้วมีโอกาสได้ไข่ระดับสูงขึ้น ถ้าตรงสูตรโอกาสจะมากขึ้น ไม่ได้ก็ได้ไข่สายพันธุ์พ่อหรือแม่",
    gotEgg: (egg: string) => `ได้${egg}!`,
    upgraded: "โชคดีมาก! ได้ไข่ระดับสูงขึ้น",
    guaranteed: "การันตีครบแล้ว!",
    discovered: (name: string) => `ค้นพบสูตรใหม่: ${name}`,
    pityTitle: "ความคืบหน้าการันตี",
    pity: (tier: string, n: number, max: number) => `${tier}: ผสมไม่ได้ระดับสูงขึ้นติดกัน ${n}/${max} ครั้ง`,
    pityLeft: (n: number) => (n <= 0 ? "ครั้งถัดไปได้แน่!" : `อีก ${n} ครั้งการันตี`),
    recipesTitle: "สูตรที่ค้นพบ",
    unknownRecipe: "??? สูตรที่ยังไม่ค้นพบ",
    recipeHint: "ค้นพบสูตรได้จากการผสมตรงสูตรสำเร็จครั้งแรก หรือรางวัลเควส",
  },
  helpers: {
    title: "ไอเท็มตัวช่วย",
    none: "ไม่มีไอเท็มตัวช่วย ซื้อได้ที่ร้านค้า",
    noHint: "ข้อนี้ไม่มีคำใบ้",
    onlyMcq: "ใช้ได้เฉพาะข้อ 4 ตัวเลือก",
    noTimer: "ข้อนี้ไม่จับเวลา",
    hint: (text: string) => `💡 คำใบ้: ${text}`,
    addTime: (n: number) => `⏳ เวลาเพิ่ม ${n} วินาที`,
    used: "ใช้แล้ว",
  },
  battleItem: {
    button: "ไอเท็ม",
    title: "ใช้ไอเท็มฟื้นฟู (เสีย 1 เทิร์น)",
    none: "ไม่มีไอเท็มฟื้นฟู",
    pickTarget: (item: string) => `ใช้${item}กับตัวไหน?`,
    used: (item: string, name: string) => `ใช้${item}กับ${name}`,
  },
  catalog: {
    title: "สมุดภาพ",
    progress: (n: number, total: number) => `${n}/${total} ช่อง`,
    tabMonsters: "มอนสเตอร์",
    tabRewards: "รางวัลสะสม",
    unknown: "???",
    hint: (text: string) => `ใบ้: ${text}`,
    seen: "เคยพบ",
    owned: "มีแล้ว",
    notOwned: "ยังไม่มี — จับหรือเลี้ยงให้ถึงร่างนี้เพื่อดูข้อมูลครบ",
    neverSeen: "ยังไม่เคยพบ",
    baseStats: "ค่าพลังพื้นฐาน",
    didYouKnow: "รู้ไหม?",
    forms: "สายวิวัฒน์",
    habitatLand: "บนบก",
    habitatWater: "ในน้ำ",
    reward: (pct: number) => `ครบ ${pct}%`,
    claimed: "ได้รับแล้ว",
    locked: "ยังไม่ถึง",
    titleLabel: "ฉายา",
    frameLabel: "กรอบโปรไฟล์",
    use: "ใช้",
    using: "กำลังใช้",
    unuse: "เลิกใช้",
    coins: (n: number) => `${n} เหรียญ`,
    tier: { common: "ธรรมดา", good: "ดี", rare: "หายาก" } as Record<string, string>,
    unlocked: (pct: number) => `สมุดภาพครบ ${pct}%! ได้รับรางวัล`,
    rarity: { normal: "ธรรมดา", rare: "หายาก", legend: "ตำนาน" } as Record<string, string>,
  },
  notice: {
    team_healed: "น้ำพุฟื้นพลังให้มอนสเตอร์ในทีมจนเต็มแล้ว",
    no_questions: "ยังไม่มีคำถามที่ครูอนุมัติ จึงยังต่อสู้ไม่ได้",
    egg_ready: "🥚 ไข่พร้อมฟักแล้ว! เปิดเมนู → ไข่และแล็บ",
    party_full: "ปาร์ตี้เต็มแล้ว (ไม่เกิน 5 คน)",
    choose_boss: "หัวหน้าต้องเลือกบอสก่อนเข้า",
    dungeon_error: "เปิดดันเจี้ยนไม่สำเร็จ ลองใหม่อีกครั้ง",
  } as Record<string, string>,
  dungeon: {
    enter: (name: string) => `🏰 ${name}`,
    unlock: (lv: number) => `ปลดล็อกที่เลเวล ${lv}`,
    locked: (lv: number) => `ต้องเลเวลผู้เล่น ${lv} ก่อน`,
    ready: "เข้าได้เลย",
    cooldown: (time: string) => `เข้าได้อีกใน ${time}`,
    cooldownHint: (n: number) => `เข้าดันเจี้ยนได้ ${n} ครั้งต่อชั่วโมง (รวมทุกดันเจี้ยน นับตอนเข้า)`,
    structure: (waves: number) => `มอนสเตอร์มลพิษ ${waves} ระลอก → บอส 2 เฟส (HP เหลือครึ่งมี "คำถามทีม": ตอบถูกเกินครึ่ง โล่บอสแตก!)`,
    boss: "บอส",
    chooseBoss: "เลือกบอส (ได้ตัวที่เลือกถ้าดรอป)",
    drops: (pct: number) => `ดรอป ${pct}% (สุ่มแยกรายคน)`,
    shardHint: (need: number) => `ไม่ได้มอน = ได้เศษพลังชีวิต 1 ชิ้น ครบ ${need} ชิ้นแลกตัวที่ต้องการได้`,
    topics: "หัวข้อคำถาม",
    guaranteed: (coins: number, exp: number) => `รางวัลการันตีทุกคน: 🪙 ${coins} · EXP ${exp} · หีบสมบัติ 1 หีบ`,
    party: "ปาร์ตี้",
    leader: "หัวหน้า",
    openParty: "เปิดปาร์ตี้ (รอเพื่อน)",
    solo: "เข้าคนเดียว",
    joinParty: (name: string) => `เข้าร่วมปาร์ตี้ของ${name}`,
    leaveParty: "ออกจากปาร์ตี้",
    start: "⚔ เข้าดันเจี้ยน",
    waitLeader: "รอหัวหน้ากดเข้า…",
    partyHint: (r: number) => `เพื่อนที่ยืนหน้าทางเข้า (ห่างไม่เกิน ${r} ช่อง) กดเข้าร่วมได้`,
    notReady: "ยังเข้าไม่ได้:",
    reason: {
      level: (lv?: number) => `เลเวลไม่ถึง ${lv ?? ""}`,
      cooldown: (time: string) => `ติดคูลดาวน์อีก ${time}`,
      busy: () => "กำลังต่อสู้อยู่",
      far: () => "ไม่ได้ยืนหน้าทางเข้า",
      offline: () => "หลุดการเชื่อมต่อ",
    },
    entering: "กำลังเข้าดันเจี้ยน…",
    stage: (i: number, n: number) => `ห้อง ${i}/${n}`,
    stageWave: (i: number) => `ระลอกที่ ${i}: มอนสเตอร์มลพิษ!`,
    stageBoss: (name: string) => `ห้องบอส: ${name}`,
    waitingParty: "รอเพื่อนในปาร์ตี้เข้ามา…",
    leave: "ออกจากดันเจี้ยน",
    leaveConfirm: "ออกจากดันเจี้ยนตอนนี้? (นับครั้งที่เข้าไปแล้ว และจะไม่ได้รางวัล)",
    teamQuestion: "คำถามทีม! ทุกคนตอบข้อเดียวกัน",
    teamResult: (c: number, n: number) => `ทีมตอบถูก ${c}/${n}`,
    shieldBroken: "โล่บอสแตก! เทิร์นถัดไปโจมตีแรงขึ้น",
    shieldHeld: "โล่ยังไม่แตก ลองใหม่นะ",
    phase2: "บอสเข้าเฟส 2! ได้ท่าใหม่และคำถามยากขึ้น",
    waitingAllies: "รอเพื่อนตอบ…",
    knockedOut: "มอนสเตอร์หมดแรงทั้งทีม — เชียร์เพื่อนต่อได้เลย ห้องถัดไปจะได้พักฟื้น",
    nextRoom: "ไปห้องถัดไป",
    seeRewards: "ดูรางวัล",
    stageClear: (i: number) => `ผ่านห้องที่ ${i}!`,
    clear: "พิชิตดันเจี้ยนสำเร็จ!",
    cleansed: (name: string) => `${name} กลับเป็นปกติแล้ว`,
    fail: "ปาร์ตี้หมดแรง…",
    failHint: "ไม่เป็นไรนะ! กลับไปพักที่น้ำพุ มอนสเตอร์หายเหนื่อยแล้ว ลองใหม่ได้เมื่อพ้นคูลดาวน์",
    drop: (name: string) => `ได้ ${name}!`,
    shard: (rarity: string, n: number, need: number) => `ได้เศษพลังชีวิต (${rarity}) — มี ${n}/${need} ชิ้น`,
    coins: (n: number) => `เหรียญ +${n}`,
    exp: (n: number) => `EXP ผู้เล่น +${n}`,
    chest: "ของในหีบ:",
    back: "กลับสู่แผนที่",
    ally: {
      attack: (name: string, dmg: number) => `${name} โจมตี -${dmg}`,
      miss: (name: string) => `${name} ตอบพลาด`,
      hit: (name: string, dmg: number) => `บอสโจมตี ${name} -${dmg}`,
      faint: (name: string) => `มอนของ ${name} หมดแรง`,
      switch: (name: string) => `${name} สลับตัว`,
      item: (name: string) => `${name} ใช้ไอเท็ม`,
      out: (name: string) => `${name} ออกจากการต่อสู้`,
    } as Record<string, (name: string, dmg: number) => string>,
  },
  shards: {
    tab: "เศษพลังชีวิต",
    have: (rarity: string, n: number, need: number) => `${rarity}: ${n}/${need} ชิ้น`,
    hint: "ได้จากดันเจี้ยนเมื่อสุ่มไม่ได้มอนสเตอร์ ครบแล้วแลกตัวที่ต้องการได้เลย",
    exchange: "แลก",
    got: (name: string) => `แลก ${name} สำเร็จ!`,
    disabled: "ตอนนี้ปิดระบบเศษพลังชีวิตอยู่",
  },
  battle: {
    appear: (name: string, lv: number) => `${name} Lv. ${lv} ปรากฏตัว!`,
    choose: "จะใช้ท่าไหนดี?",
    waiting: "รอสักครู่…",
    switchBtn: "สลับตัว",
    switchTitle: "เลือกมอนสเตอร์ที่จะออกไปสู้",
    switchHint: "สลับตัวเสีย 1 เทิร์น",
    flee: "หนี",
    back: "ย้อนกลับ",
    cooldown: (n: number) => `รอ ${n} เทิร์น`,
    power: (p: number) => `พลัง ${p}`,
    fainted: "หมดแรง",
    active: "กำลังสู้",
    question: "ตอบให้ถูกเพื่อโจมตี!",
    choiceLabels: ["ก", "ข", "ค", "ง"],
    trueLabel: "ถูก",
    falseLabel: "ผิด",
    numericPlaceholder: "พิมพ์ตัวเลข",
    submit: "ตอบ",
    item: "ใช้ไอเท็ม",
    itemSoon: "ใช้ไอเท็มได้ในเฟส 7",
    timeUp: "หมดเวลา!",
    seconds: (n: number) => `${n} วิ`,
    correct: "ถูกต้อง!",
    quick: "ตอบไว! พลังโจมตี ×1.2",
    wrong: "ยังไม่ถูก",
    timedOut: "หมดเวลา",
    answerIs: (text: string) => `คำตอบที่ถูก: ${text}`,
    explanation: "คำอธิบาย",
    next: "ต่อไป",
    nextIn: (n: number) => `ต่อไป (${n})`,
    missed: "พลาด!",
    super: "ได้ผลดีมาก!",
    weak: "ไม่ค่อยได้ผล…",
    decay: (n: number) => `ย่อยสลาย ×${n}`,
    stat: { hp: "HP", atk: "ATK", def: "DEF", spd: "SPD" } as Record<string, string>,
    faint: (name: string) => `${name} หมดแรง!`,
    go: (name: string) => `ไปเลย ${name}!`,
    win: "ชนะแล้ว!",
    caught: (name: string) => `ได้${name}มาเป็นเพื่อนแล้ว!`,
    newSpecies: "ใหม่! บันทึกลงสมุดภาพ",
    toTeam: "เข้าร่วมทีมแล้ว",
    toStorage: "ทีมเต็ม ส่งไปที่คลังแล้ว",
    toBox: "คลังเต็ม ฝากไว้ที่กล่องพักก่อน",
    lose: "คู่หูหมดแรงทั้งทีม…",
    loseHint: "ไม่เป็นไรนะ! พากลับไปพักที่น้ำพุ มอนสเตอร์หายเหนื่อยแล้ว ไม่เสียของใด ๆ",
    fled: "หนีมาได้อย่างปลอดภัย",
    score: (c: number, n: number) => `ตอบถูก ${c}/${n} ข้อ`,
    playerExp: (n: number) => `EXP ผู้เล่น +${n}`,
    coins: (n: number) => `เหรียญ +${n}`,
    monsterExp: (name: string, n: number) => `${name} EXP +${n}`,
    levelUp: (name: string, from: number, to: number) => `${name} เลเวลอัป! Lv. ${from} → ${to}`,
    newMove: (name: string) => `เรียนรู้ท่าใหม่: ${name}`,
    playerLevelUp: (from: number, to: number) => `เลเวลผู้เล่นอัป! Lv. ${from} → ${to}`,
    backToMap: "กลับสู่แผนที่",
    busy: "มอนตัวนี้กำลังต่อสู้กับคนอื่นอยู่",
  },
  dev: {
    title: "โหมดทดสอบ",
    give: "ให้",
    remove: "เอาออก",
    summon: "⚔ เรียกมอนป่ามาข้างหน้า",
  },
} as const;
