// ข้อความของหน้าครู (หัวข้อ 11.6)

export const T = {
  title: "EcoMon Quest · หน้าครู",
  loading: "กำลังโหลด…",
  auth: {
    login: "เข้าสู่ระบบ",
    register: "สมัครบัญชีครู",
    username: "ชื่อผู้ใช้",
    usernameHint: "ภาษาอังกฤษตัวเล็ก ตัวเลข _ . -",
    password: "รหัสผ่าน",
    passwordHint: "อย่างน้อย 8 ตัวอักษร",
    displayName: "ชื่อที่แสดง",
    inviteCode: "รหัสเชิญของโรงเรียน",
    inviteHint: "ขอจากผู้ดูแลระบบ",
    submitLogin: "เข้าสู่ระบบ",
    submitRegister: "สมัครและเข้าสู่ระบบ",
    toGame: "← กลับไปหน้าเกม",
  },
  logout: "ออกจากระบบ",
  classrooms: "ห้องเรียนของฉัน",
  noClassrooms: "ยังไม่มีห้องเรียน สร้างห้องใหม่หรือรับดูแลห้องที่มีอยู่ด้วยรหัสห้องเรียน",
  students: (n: number) => `นักเรียน ${n} คน`,
  code: "รหัสห้องเรียน",
  codeHint: "ให้นักเรียนใช้รหัสนี้ตอนเข้าเกม",
  createName: "ชื่อห้องเรียน เช่น ม.6/1",
  create: "สร้างห้องเรียน",
  claimCode: "รหัสห้องเรียนที่มีอยู่",
  claim: "รับดูแล",
  tabs: { report: "ผลการเรียน", questions: "คลังคำถาม", settings: "ตั้งค่าห้องเรียน" },
  report: {
    pick: "เลือกห้องเรียนทางซ้าย",
    metric: "แสดง",
    rate: "% ตอบถูก",
    mastery: "ค่าความชำนาญ",
    student: "นักเรียน",
    level: "Lv.",
    total: "รวม",
    lastSeen: "เข้าเล่นล่าสุด",
    none: "—",
    noStudents: "ยังไม่มีนักเรียนในห้องนี้",
    cellTitle: (topic: string, correct: number, answered: number, mastery: number | null) =>
      `${topic}: ถูก ${correct}/${answered} ข้อ${mastery !== null ? ` · ความชำนาญ ${mastery}` : ""}`,
    missed: "ข้อที่ผิดบ่อยที่สุด 10 ข้อ",
    missedNone: "ยังไม่มีข้อที่ตอบผิด",
    wrong: (wrong: number, answered: number) => `ผิด ${wrong}/${answered} ครั้ง`,
    export: "ส่งออก CSV",
    refresh: "รีเฟรช",
    legend: "สี: แดง = ยังไม่เข้าใจ → เขียว = เข้าใจดี · ช่องเทา = ยังไม่เคยตอบ",
    csvHead: ["ชื่อเล่น", "เลเวล", "ตอบทั้งหมด", "ตอบถูก", "% ถูก"],
    csvTopic: (name: string) => [`${name} (ถูก/ทั้งหมด)`, `${name} % ถูก`, `${name} ความชำนาญ`],
    csvMissed: ["ข้อที่ผิดบ่อย", "หัวข้อ", "ผิด", "ตอบทั้งหมด", "id"],
  },
  questions: {
    filterTopic: "หัวข้อ",
    filterStatus: "สถานะ",
    filterSource: "ที่มา",
    search: "ค้นหาโจทย์หรือ id",
    all: "ทั้งหมด",
    status: { draft: "ร่าง (รออนุมัติ)", approved: "อนุมัติแล้ว", retired: "ถอนออก" } as Record<string, string>,
    source: { content: "ไฟล์ของเกม", custom: "ครูนำเข้า" } as Record<string, string>,
    type: { mcq: "ปรนัย", image_mcq: "ปรนัยมีภาพ", truefalse: "ถูก/ผิด", numeric: "เติมตัวเลข" } as Record<string, string>,
    count: (shown: number, total: number) => `แสดง ${shown} จาก ${total} ข้อ`,
    approve: "อนุมัติ",
    toDraft: "กลับเป็นร่าง",
    retire: "ถอนออก",
    approveShown: (n: number) => `อนุมัติร่างที่แสดงทั้งหมด (${n})`,
    confirmApproveAll: (n: number) => `อนุมัติคำถามร่าง ${n} ข้อที่แสดงอยู่?`,
    answer: "เฉลย",
    explanation: "คำอธิบาย",
    hint: "คำใบ้",
    trueText: "ถูก",
    falseText: "ผิด",
    numeric: (v: number, tol: number, unit?: string) => `${v}${unit ? ` ${unit}` : ""}${tol ? ` (±${tol})` : ""}`,
    meta: (id: string, difficulty: number, author: string) => `${id} · ระดับ ${difficulty} · ${author}`,
    stats: (correct: number, answered: number) => (answered ? `ตอบถูก ${correct}/${answered} (${Math.round((correct / answered) * 100)}%)` : "ยังไม่มีคนตอบ"),
    import: "นำเข้าคำถามจาก CSV",
    importHint: "คอลัมน์: id, topic, difficulty (1–3), type (mcq/truefalse/numeric/image_mcq), stem, choice_a–d, answer (a–d / true-false / ตัวเลข), tolerance, unit, explanation, hint, image, tags · ข้อที่นำเข้าเป็น \"ร่าง\" จนกว่าครูอนุมัติ",
    template: "ดาวน์โหลดแม่แบบ CSV",
    pickFile: "เลือกไฟล์ CSV",
    paste: "หรือวางข้อความ CSV ที่นี่ (เช่นคัดลอกจาก Google Sheet ที่ส่งออกเป็น CSV)",
    check: "ตรวจก่อน",
    doImport: "นำเข้า",
    result: (added: number, updated: number, errors: number) => `ข้อใหม่ ${added} · แก้ไข ${updated} · แถวที่ผิด ${errors}`,
    imported: (added: number, updated: number) => `นำเข้าแล้ว: ข้อใหม่ ${added} · แก้ไข ${updated} (สถานะร่าง รออนุมัติ)`,
    row: (n: number) => `แถว ${n}`,
    empty: "ไม่มีคำถามที่ตรงกับตัวกรอง",
  },
  settings: {
    pick: "เลือกห้องเรียนทางซ้าย",
    timer: "จับเวลาตอบคำถาม",
    timerHint: "ปิด = โหมดฝึก นักเรียนคิดได้ไม่จำกัดเวลา",
    topics: "หัวข้อที่ใช้ถาม (ตามที่สอนถึง)",
    allTopics: "ทุกหัวข้อ",
    topicsHint: "ไม่เลือกเลย = ใช้ทุกหัวข้อ",
    dungeon: "จำนวนครั้งเข้าดันเจี้ยน",
    dungeonHint: (n: number, minutes: number) => `เว้นว่าง = ค่าเริ่มต้นของเกม (${n} ครั้งต่อ ${minutes} นาที)`,
    save: "บันทึก",
    saved: "บันทึกแล้ว",
  },
  time: {
    never: "ยังไม่เคย",
    ago: (ms: number) => {
      const m = Math.floor(ms / 60000);
      if (m < 1) return "เมื่อสักครู่";
      if (m < 60) return `${m} นาทีที่แล้ว`;
      const h = Math.floor(m / 60);
      if (h < 24) return `${h} ชั่วโมงที่แล้ว`;
      return `${Math.floor(h / 24)} วันที่แล้ว`;
    },
  },
};
